/*SELECT * FROM EQUIPOFUTBOL*/

/*INSERT INTO EQUIPOFUTBOL (RUT,NOMBRE,EDAD,CAMISETA) VALUES ('1-9','Cristian',29,17);*/

/*SELECT * FROM EQUIPOFUTBOL*/

/*INSERT INTO EQUIPOFUTBOL (RUT,NOMBRE,EDAD,CAMISETA) VALUES ('2-9','Memo',33,19);*/

/*SELECT * FROM EQUIPOFUTBOL*/

