
CREATE TABLE PERSONA (
ID_PERSONA INT PRIMARY KEY AUTO_INCREMENT,
RUT VARCHAR(10) NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO_PAT VARCHAR(30) NOT NULL,
EDAD INT NOT NULL,
HOBBY VARCHAR(40)
);



CREATE TABLE TELEFONO (
ID_TELEFONO INT PRIMARY KEY AUTO_INCREMENT,
TELEFONO VARCHAR(12) NOT NULL,
ID_PERSONA_FK INT NOT NULL,
FOREIGN KEY (ID_PERSONA_FK) REFERENCES PERSONA(ID_PERSONA)
);hibernatepersonacliente